- src/main/java/uk/gov/cshr/civilservant/resource/CivilServantResource.java
> [LPFG-49][LPFG-278][BUG] Missing resource

- src/main/java/uk/gov/cshr/civilservant/domain/CivilServant.java
- src/main/java/uk/gov/cshr/civilservant/resource/CivilServantResource.java
- src/main/resources/schema-mysql.sql
> Add other areas of work

- src/main/java/uk/gov/cshr/civilservant/controller/CivilServantController.java
Updated relationship between civil servant and organisationalUnit
> LPFG-820: Update lpg-services to call new organisationalUnit endpoint in CSRS

- src/main/java/uk/gov/cshr/civilservant/config/RepositoryConfig.java
- src/main/java/uk/gov/cshr/civilservant/domain/OrganisationalUnit.java
- src/main/java/uk/gov/cshr/civilservant/repository/OrganisationalUnitRepository.java
- src/main/java/uk/gov/cshr/civilservant/service/OrganisationalUnitService.java
- src/test/java/uk/gov/cshr/civilservant/repository/OrganisationalUnitRepositoryTest.java
- cleaning up parent/sub-org relationship
- adding missing repo tests
> LPFG-929: Add organisations

- src/main/resources/db/migration/h2/V1.1__data.sql
- src/main/resources/db/migration/mysql/V1.9__change-casing-of-grades.sql
_branched off: https://github.com/Civil-Service-Human-Resources/civil-servant-registry-service/pull/43_
- changing ordering of grades
> LPFG 1056 - Change ordering of grades

- src/main/java/uk/gov/cshr/civilservant/controller/ProfessionController.java
- src/main/java/uk/gov/cshr/civilservant/domain/CivilServant.java
- src/main/java/uk/gov/cshr/civilservant/domain/SelfReferencingEntity.java
**branches off of fix/lazy-initialize-collection, so should be merged after that**
Added an endpoint to **ProfessionController.java** to get professions in a flat structure.
> LPFG-1255: Flat professions endpoint

- src/main/java/uk/gov/cshr/civilservant/dto/factory/CivilServantDtoFactory.java
- src/main/java/uk/gov/cshr/civilservant/service/ReportService.java
- src/test/java/uk/gov/cshr/civilservant/dto/factory/CivilServantDtoFactoryTest.java
- removing transactional to determine if more performant
> LC-164: slow running csrs query

- src/main/resources/db/migration/h2/V1.10__update-interests.sql
- src/main/resources/db/migration/h2/V1.9__change-casing-of-grades.sql
- src/main/resources/db/migration/mysql/V1.10__update-interests.sql
- updating interests
- adding local h2 migrations for consistency
> LC-102: updating interests

- src/main/java/uk/gov/cshr/civilservant/controller/CivilServantController.java
- src/test/java/uk/gov/cshr/civilservant/controller/CivilServantControllerTest.java
Added a privileged endpoint to delete a civil servant from the csrs db
> Lpfg 1273 delete user

- src/main/java/uk/gov/cshr/civilservant/controller/CivilServantController.java
- src/main/java/uk/gov/cshr/civilservant/controller/ReportController.java
- src/main/java/uk/gov/cshr/civilservant/domain/CivilServant.java
- src/main/java/uk/gov/cshr/civilservant/dto/CivilServantDto.java
- src/main/java/uk/gov/cshr/civilservant/repository/CivilServantRepository.java
- src/main/java/uk/gov/cshr/civilservant/service/ReportService.java
- src/test/java/uk/gov/cshr/civilservant/controller/CivilServantControllerTest.java
- src/test/java/uk/gov/cshr/civilservant/controller/ReportControllerTest.java
- writing custom civil servant repo query to determine impact on performance
> Lc 161 custom civilservantrepo query

- src/main/java/uk/gov/cshr/civilservant/config/CustomMySqlDialect.java
- src/main/java/uk/gov/cshr/civilservant/controller/ReportController.java
- src/main/java/uk/gov/cshr/civilservant/dto/CivilServantReportDto.java
- src/main/java/uk/gov/cshr/civilservant/repository/CivilServantRepository.java
- src/main/java/uk/gov/cshr/civilservant/service/ReportService.java
- src/main/resources/application.yml
- src/test/java/uk/gov/cshr/civilservant/controller/ReportControllerTest.java
- mi updates to include other areas of work
> Lc 223 mi updates

- src/main/java/uk/gov/cshr/civilservant/dto/factory/ProfessionDtoFactory.java
- formatting professions name for typeahead
> LPFG-1255: adding format name function to profession factory

- src/main/java/uk/gov/cshr/civilservant/controller/CivilServantController.java
- src/main/java/uk/gov/cshr/civilservant/domain/CivilServant.java
> LPFG-1139-data-retention

- src/main/java/uk/gov/cshr/civilservant/controller/QuizController.java
- src/main/java/uk/gov/cshr/civilservant/domain/Question.java
- src/main/java/uk/gov/cshr/civilservant/repository/ProfessionRepository.java
- src/main/resources/db/migration/h2/V1.11__skills.sql
- src/main/resources/db/migration/h2/V1.8__professions.sql
- src/main/resources/db/migration/mysql/V1.12__question_theme.sql
> LC-103: Skills pr updates

- src/main/java/uk/gov/cshr/civilservant/controller/OrganisationalUnitController.java
- src/main/java/uk/gov/cshr/civilservant/domain/OrganisationalUnit.java
- src/main/java/uk/gov/cshr/civilservant/repository/OrganisationalUnitRepository.java
- src/main/java/uk/gov/cshr/civilservant/service/OrganisationalUnitService.java
- src/main/resources/application.yml
> LC-244: improving performace for orgs

- build.gradle
- src/main/java/uk/gov/cshr/civilservant/Application.java
- src/main/java/uk/gov/cshr/civilservant/controller/OrganisationalUnitController.java
- src/main/java/uk/gov/cshr/civilservant/repository/OrganisationalUnitRepository.java
- src/main/java/uk/gov/cshr/civilservant/repository/SelfReferencingEntityRepository.java
- src/main/java/uk/gov/cshr/civilservant/service/OrganisationalUnitService.java
- src/main/resources/application.yml
> LC-244: initial caching

- src/main/java/uk/gov/cshr/civilservant/controller/AgencyTokenController.java
- src/main/java/uk/gov/cshr/civilservant/domain/AgencyToken.java
- src/main/java/uk/gov/cshr/civilservant/repository/AgencyTokenRepository.java
- src/main/java/uk/gov/cshr/civilservant/service/AgencyTokenService.java
- src/test/java/uk/gov/cshr/civilservant/controller/AgencyTokenControllerTest.java
- src/test/java/uk/gov/cshr/civilservant/service/AgencyTokenServiceTest.java
- branching off to set up validation for agency token validation
- added new `capacity used` field
> LC-14: agencytoken endpoints for validation

- src/main/java/uk/gov/cshr/civilservant/controller/OrganisationalUnitController.java
- src/main/java/uk/gov/cshr/civilservant/service/AgencyTokenService.java
- src/main/java/uk/gov/cshr/civilservant/service/OrganisationalUnitService.java
- src/test/java/uk/gov/cshr/civilservant/service/OrganisationalUnitServiceTest.java
- endpoints for self sign up validation and verification
> LC-14: agency self-sign up endpoints

- src/main/java/uk/gov/cshr/civilservant/controller/OrganisationalUnitController.java
- src/main/java/uk/gov/cshr/civilservant/controller/ReportController.java
- src/main/java/uk/gov/cshr/civilservant/dto/CivilServantReportDto.java
- src/main/java/uk/gov/cshr/civilservant/repository/CivilServantRepository.java
- src/main/java/uk/gov/cshr/civilservant/repository/OrganisationalUnitRepository.java
- src/main/java/uk/gov/cshr/civilservant/service/OrganisationalUnitService.java
- src/main/java/uk/gov/cshr/civilservant/service/ReportService.java
- src/main/resources/application.yml
- src/test/java/uk/gov/cshr/civilservant/controller/OrganisationalUnitControllerTest.java
- src/test/java/uk/gov/cshr/civilservant/service/OrganisationalUnitServiceTest.java
- adding endpoint to get map of codes and parent codes
> fix: adding endpoint to get map of codes and parent codes

- src/main/java/uk/gov/cshr/civilservant/controller/CivilServantController.java
- src/main/resources/application.yml
- updating pre-auth to permit client connections to delete endpoint
> fix: fix-preauth-of-delete-endpoint

- Dockerfile
- build.gradle
- lib/AI-Agent.xml
- src/main/resources/ApplicationsInsights.xml
- src/test/java/uk/gov/cshr/civilservant/controller/CivilServantControllerTest.java
- src/test/java/uk/gov/cshr/civilservant/controller/OrganisationalUnitControllerTest.java
- src/test/java/uk/gov/cshr/civilservant/controller/ProfessionControllerTest.java
- src/test/java/uk/gov/cshr/civilservant/controller/ReportControllerTest.java
- src/test/java/uk/gov/cshr/civilservant/utils/MockMVCFilterOverrider.java
This work is about adding AZ App Insights. Main changes are
1. build.gradle. Bring in dependencies
2.ApplicationsInsights.xml. Telementry configurations
3.AI-Agent.xml. config file for the java agent
4.  Dockerfile. add files from point 3 above
> add Azure App Insights

- src/main/java/uk/gov/cshr/civilservant/controller/CivilServantController.java
- src/main/java/uk/gov/cshr/civilservant/dto/CivilServantDto.java
- src/main/java/uk/gov/cshr/civilservant/dto/factory/CivilServantDtoFactory.java
- src/main/java/uk/gov/cshr/civilservant/resource/CivilServantResource.java
- src/main/java/uk/gov/cshr/civilservant/resource/factory/CivilServantResourceFactory.java
- src/test/java/uk/gov/cshr/civilservant/controller/CivilServantControllerTest.java
- src/test/java/uk/gov/cshr/civilservant/dto/factory/CivilServantDtoFactoryTest.java
- src/test/java/uk/gov/cshr/civilservant/resource/factory/CivilServantResourceFactoryTest.java
Fixes for all the issues to do with the change email on profile page scenario.
> Bugfix lc 14 find old org code

- src/main/java/uk/gov/cshr/civilservant/config/OAuthProperties.java
- src/main/java/uk/gov/cshr/civilservant/config/SecurityConfig.java
- src/main/resources/application.yml
Added "PoolingHttpClientConnectionManager" to be used by OAuth2RestTemplate in order to increase its efficiency. The manager is also configurable.
> Implemented PoolingHttpClientConnectionManager to be used for requests

- src/main/java/uk/gov/cshr/civilservant/controller/CivilServantController.java
Removed isAuthenticated() from delete org from civil servant.
> LC-332 - Removed isAuthenticated() from delete org from civil servant.

- src/main/java/uk/gov/cshr/civilservant/config/OAuthProperties.java
- src/main/java/uk/gov/cshr/civilservant/config/SecurityConfig.java
- src/main/resources/application.yml
> Release performance release e2

- src/main/java/uk/gov/cshr/civilservant/controller/CivilServantController.java
- src/main/java/uk/gov/cshr/civilservant/service/LineManagerService.java
- src/test/java/uk/gov/cshr/civilservant/controller/CivilServantControllerTest.java
Release branch for f2f
Include PRs:
https://github.com/Civil-Service-Human-Resources/civil-servant-registry-service/pull/83
> Releases f2f features

- src/main/java/uk/gov/cshr/civilservant/validation/ValidAgencyTokenCapacityValidator.java
Reordering conditional of capacity validator
> hotfix: reordering conditional

- src/main/java/uk/gov/cshr/civilservant/controller/OrganisationalUnitController.java
- src/main/java/uk/gov/cshr/civilservant/repository/OrganisationalUnitRepository.java
- adding caching to org unit find all repository method
- adding missing sorting method to stream
> LC-14: adding caching to org unit find all repository method

- src/main/java/uk/gov/cshr/civilservant/dto/QuizDataTableDto.java
- src/main/java/uk/gov/cshr/civilservant/service/QuizService.java
- src/test/java/uk/gov/cshr/civilservant/service/QuizServiceTest.java
> Fix for zero average score display

- src/main/java/uk/gov/cshr/civilservant/controller/CivilServantController.java
- src/main/java/uk/gov/cshr/civilservant/repository/CivilServantRepository.java
- src/main/java/uk/gov/cshr/civilservant/resource/CivilServantResource.java
- src/main/java/uk/gov/cshr/civilservant/resource/factory/CivilServantResourceFactory.java
Reverts Civil-Service-Human-Resources/civil-servant-registry-service#129
> Revert "Lcs 654 incompleted courses fetch by days"

- src/main/java/uk/gov/cshr/civilservant/domain/OrganisationalUnit.java
- src/main/java/uk/gov/cshr/civilservant/service/OrganisationalUnitService.java
LC-823 organisations and their children sorting based on the name.
> LC-823 organisations and their children sorting based on the name

- src/main/java/uk/gov/cshr/civilservant/controller/HealthController.java
This change:
* Adds a `/health` endpoint to be used for health checks
> Add healthcheck endpoint

- src/main/resources/db/migration/h2/V1.18__update-civil_servant-add-unique-constraint.sql
- src/main/resources/db/migration/mysql/V1.18__update-civil_servant-add-unique-constraint.sql
> LC-1560 - Apply unique constraint on identity_id column in csrs.civil_servant table

- src/main/java/uk/gov/cshr/civilservant/controller/OrganisationalUnitController.java
- src/main/java/uk/gov/cshr/civilservant/domain/OrganisationalUnit.java
- src/main/java/uk/gov/cshr/civilservant/dto/RemoveDomainFromOrgResponse.java
- src/main/java/uk/gov/cshr/civilservant/service/OrganisationalUnitService.java
- src/test/java/uk/gov/cshr/civilservant/integration/OrganisationUnitIntegrationTest.java
- Remove domains from organisation endpoint
- Include sub org filter
> LC 2341 remove domains from org

- src/main/java/uk/gov/cshr/civilservant/controller/CivilServantController.java
- src/main/java/uk/gov/cshr/civilservant/dto/CivilServantProfileDto.java
- src/main/java/uk/gov/cshr/civilservant/dto/GradeDto.java
- src/main/java/uk/gov/cshr/civilservant/dto/factory/CivilServantProfileDtoFactory.java
- src/main/java/uk/gov/cshr/civilservant/dto/factory/ProfessionDtoFactory.java
- src/main/java/uk/gov/cshr/civilservant/resource/CivilServantResource.java
- src/main/java/uk/gov/cshr/civilservant/resource/factory/CivilServantResourceFactory.java
- src/main/java/uk/gov/cshr/civilservant/service/CivilServantService.java
- src/test/java/uk/gov/cshr/civilservant/integration/CivilServantControllerIntegrationTest.java
- src/test/java/uk/gov/cshr/civilservant/resource/factory/CivilServantResourceFactoryTest.java
- Introduce a new endpoint for fetching the complete profile for a Civil Servant. This includes their CSRS data as well as their identity profile.
> LC 2775 send completions

- src/main/java/uk/gov/cshr/civilservant/service/CivilServantService.java
- src/main/java/uk/gov/cshr/civilservant/service/identity/IdentityDTO.java
- src/test/java/uk/gov/cshr/civilservant/service/CivilServantServiceTest.java
- Add an extra check to the login endpoint to check for unrestricted login
> LC-2944 Check for unrestricted organisation on login

- build.gradle
- src/main/java/uk/gov/cshr/civilservant/dto/CivilServantProfileDto.java
- src/main/java/uk/gov/cshr/civilservant/dto/factory/CivilServantProfileDtoFactory.java
- src/main/java/uk/gov/cshr/civilservant/service/CivilServantService.java
- src/test/java/uk/gov/cshr/civilservant/integration/BaseIntegrationTest.java
- src/test/java/uk/gov/cshr/civilservant/integration/CivilServantControllerIntegrationTest.java
- src/test/resources/db/migration/h2/V1.999__civil_servant_data.sql
- Include user's line manager data in GET profile endpoint
> LC-3177 Return line manager data using profile endpoint

- src/main/java/uk/gov/cshr/civilservant/controller/CivilServantController.java
- src/main/java/uk/gov/cshr/civilservant/repository/CivilServantRepository.java
- src/main/java/uk/gov/cshr/civilservant/resource/factory/CivilServantResourceFactory.java
- Implement pagination on the `GET /civilservants/organisation` endpoint
- Return civil servant UIDs from this endpoint instead of full Civil Servant objects
> LC-3482 fetch civil servant UIDs with org code
